apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: tpg
  labels:
    app: order-service
    group: general
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        group: general
        version: v1
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 60